name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore PicsDataCollector/PicsDataCollector.csproj

    - name: Build
      run: dotnet build PicsDataCollector/PicsDataCollector.csproj --configuration Release --no-restore

    - name: Build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ Build completed successfully" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Project Details" >> $GITHUB_STEP_SUMMARY
        echo "- **Configuration**: Release" >> $GITHUB_STEP_SUMMARY
        echo "- **.NET Version**: 8.0.x" >> $GITHUB_STEP_SUMMARY
